"""Application-owned persistence contracts, independent of PostgreSQL."""
from datetime import datetime
from typing import Protocol

BookingRow = tuple[int, datetime, str]
ClientRow = tuple[str, str]


class ClientRepository(Protocol):
    def get_by_telephone(self, telephone: str) -> ClientRow | None: ...
    def create(self, telephone: str, name: str) -> ClientRow: ...


class BookingRepository(Protocol):
    def get_request(self, request_id: str) -> BookingRow | None: ...
    def create(self, timestamp: datetime, telephone: str, request_id: str | None = None) -> BookingRow: ...
    def get_by_id(self, booking_id: int) -> BookingRow | None: ...
    def list_between(self, start: datetime, end: datetime) -> list[BookingRow]: ...
    def delete(self, booking_id: int) -> bool: ...
    def update(self, booking_id: int, timestamp: datetime | None = None, telephone: str | None = None) -> BookingRow | None: ...
