"""Application ports: one small transactional calendar, one barbershop."""

from contextlib import AbstractContextManager
from datetime import datetime
from typing import Protocol

from src.domain.calendar import Appointment, Calendar


class BarbershopTransaction(Protocol):
    def calendar(self) -> tuple[Calendar, int]: ...
    def save_calendar(self, calendar: Calendar) -> None: ...
    def customer(self, telephone: str) -> dict | None: ...
    def save_customer(self, telephone: str, name: str) -> dict: ...
    def appointments(
        self, start: datetime, end: datetime, telephone: str | None = None
    ) -> list[Appointment]: ...
    def appointment(self, identifier: int) -> Appointment | None: ...
    def insert(self, timestamp: datetime, telephone: str) -> Appointment: ...
    def move(self, identifier: int, timestamp: datetime) -> Appointment: ...
    def delete(self, identifier: int) -> None: ...
    def receipt(self, key: str) -> dict | None: ...
    def save_receipt(self, key: str, fingerprint: str, ids: list[int]) -> None: ...


class BarbershopStore(Protocol):
    def transaction(self) -> AbstractContextManager[BarbershopTransaction]: ...


# Compatibility aliases for the former calendar-oriented names.
CalendarTransaction = BarbershopTransaction
CalendarStore = BarbershopStore
